#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import os
import re
import secrets
import shutil
import sys
from pathlib import Path
from typing import Any

import yaml

SAFE_ID = re.compile(r"^[a-z0-9][a-z0-9_-]{1,62}$")
PG_UNSAFE = re.compile(r"[^a-z0-9_]+")
TOKEN_PATTERN = re.compile(r"@@[A-Z0-9_]+@@")


class ConfigError(Exception):
    pass


def load_yaml(path: Path) -> dict[str, Any]:
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError) as exc:
        raise ConfigError(f"Impossible de lire {path}: {exc}") from exc

    if not isinstance(data, dict):
        raise ConfigError(f"La racine YAML de {path} doit être un objet.")

    return data


def require_mapping(value: Any, field: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ConfigError(f"{field} doit être un objet YAML.")
    return value


def require_text(value: Any, field: str) -> str:
    text = str(value or "").strip()
    if not text:
        raise ConfigError(f"{field} est obligatoire.")
    return text


def parse_env(path: Path) -> dict[str, str]:
    result: dict[str, str] = {}
    if not path.is_file():
        return result

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        result[key.strip()] = value.strip().strip('"').strip("'")

    return result


def postgres_identifier(prefix: str, client_id: str) -> str:
    normalized = PG_UNSAFE.sub("_", client_id.replace("-", "_").lower())
    normalized = normalized.strip("_")
    if not normalized:
        raise ConfigError("Impossible de produire un identifiant PostgreSQL.")
    return f"{prefix}_{normalized}"[:63].rstrip("_")


def replace_tokens(content: str, tokens: dict[str, str]) -> str:
    rendered = content
    for key, value in tokens.items():
        rendered = rendered.replace(f"@@{key}@@", value)

    unresolved = sorted(set(TOKEN_PATTERN.findall(rendered)))
    if unresolved:
        raise ConfigError(
            "Variables de template non remplacées : " + ", ".join(unresolved)
        )
    return rendered


def write_env(path: Path, values: dict[str, str]) -> None:
    lines = ["# Generated by saas_factory. Do not commit.", ""]

    for key, value in values.items():
        if "\n" in value or "\r" in value:
            raise ConfigError(f"Valeur multiligne interdite pour {key}.")
        lines.append(f"{key}={value}")

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.chmod(path, 0o600)


def render_json_templates(
    source_dir: Path,
    destination_dir: Path,
    tokens: dict[str, str],
) -> list[str]:
    rendered_files: list[str] = []
    destination_dir.mkdir(parents=True, exist_ok=True)

    if not source_dir.is_dir():
        return rendered_files

    for template in sorted(source_dir.glob("*.template.json")):
        output_name = template.name.removesuffix(".template.json") + ".json"
        output = destination_dir / output_name
        content = replace_tokens(template.read_text(encoding="utf-8"), tokens)

        try:
            json.loads(content)
        except json.JSONDecodeError as exc:
            raise ConfigError(
                f"JSON invalide après rendu de {template}: {exc}"
            ) from exc

        output.write_text(content.rstrip() + "\n", encoding="utf-8")
        rendered_files.append(output_name)

    return rendered_files


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Génère Docker, Caddy et les secrets d'un tenant."
    )
    parser.add_argument("tenant_file", type=Path)
    parser.add_argument("factory_file", type=Path)
    parser.add_argument("output_dir", type=Path)
    parser.add_argument(
        "--template-root",
        type=Path,
        default=Path("/root/saas_factory/template"),
    )
    parser.add_argument("--force", action="store_true")
    parser.add_argument("--rotate-secrets", action="store_true")
    args = parser.parse_args()

    try:
        tenant_data = load_yaml(args.tenant_file)
        factory_data = load_yaml(args.factory_file)

        tenant = require_mapping(tenant_data.get("tenant"), "tenant")
        restaurant = require_mapping(tenant_data.get("restaurant"), "restaurant")
        factory = require_mapping(factory_data.get("factory"), "factory")

        client_id = require_text(tenant.get("client_id"), "tenant.client_id")
        if not SAFE_ID.fullmatch(client_id):
            raise ConfigError(
                "tenant.client_id doit respecter ^[a-z0-9][a-z0-9_-]{1,62}$"
            )

        restaurant_slug = require_text(
            tenant.get("restaurant_slug"), "tenant.restaurant_slug"
        )
        timezone = require_text(restaurant.get("timezone"), "restaurant.timezone")

        base_domain = require_text(factory.get("base_domain"), "factory.base_domain")
        edge_network = require_text(factory.get("edge_network"), "factory.edge_network")
        n8n_image = require_text(factory.get("n8n_image"), "factory.n8n_image")
        postgres_image = require_text(
            factory.get("postgres_image"), "factory.postgres_image"
        )
        n8n_log_level = str(factory.get("n8n_log_level", "info")).strip() or "info"

        tenant_path = client_id
        n8n_container = f"{client_id}_n8n"

        previous_env = parse_env(args.output_dir / ".env")

        # Lors d'une mise à jour, conserver les noms PostgreSQL historiques
        # présents dans le .env du tenant existant.
        postgres_db = previous_env.get("POSTGRES_DB") or postgres_identifier(
            "booking", client_id
        )
        postgres_user = previous_env.get("POSTGRES_USER") or postgres_identifier(
            "booking", client_id
        )

        if args.output_dir.exists():
            if not args.force:
                raise ConfigError(
                    f"{args.output_dir} existe déjà. Utiliser --force."
                )
            shutil.rmtree(args.output_dir)

        args.output_dir.mkdir(parents=True, exist_ok=True)

        postgres_password = (
            None if args.rotate_secrets else previous_env.get("POSTGRES_PASSWORD")
        ) or secrets.token_urlsafe(36)

        encryption_key = (
            None if args.rotate_secrets else previous_env.get("N8N_ENCRYPTION_KEY")
        ) or secrets.token_hex(32)

        env_values = {
            "COMPOSE_PROJECT_NAME": client_id,
            "CLIENT_ID": client_id,
            "RESTAURANT_SLUG": restaurant_slug,
            "TENANT_PATH": tenant_path,
            "BASE_DOMAIN": base_domain,
            "EDGE_NETWORK": edge_network,
            "TIMEZONE": timezone,
            "POSTGRES_IMAGE": postgres_image,
            "POSTGRES_DB": postgres_db,
            "POSTGRES_USER": postgres_user,
            "POSTGRES_PASSWORD": postgres_password,
            "N8N_IMAGE": n8n_image,
            "N8N_LOG_LEVEL": n8n_log_level,
            "N8N_ENCRYPTION_KEY": encryption_key,
        }
        write_env(args.output_dir / ".env", env_values)

        docker_template = (
            args.template_root / "docker" / "docker-compose.yml.template"
        )
        caddy_template = (
            args.template_root / "caddy" / "client-route.caddy.template"
        )

        if not docker_template.is_file():
            raise ConfigError(f"Template absent : {docker_template}")
        if not caddy_template.is_file():
            raise ConfigError(f"Template absent : {caddy_template}")

        shutil.copy2(docker_template, args.output_dir / "docker-compose.yml")

        tokens = {
            "CLIENT_ID": client_id,
            "RESTAURANT_SLUG": restaurant_slug,
            "TENANT_PATH": tenant_path,
            "BASE_DOMAIN": base_domain,
            "EDGE_NETWORK": edge_network,
            "TIMEZONE": timezone,
            "N8N_CONTAINER": n8n_container,
            "POSTGRES_DB": postgres_db,
            "POSTGRES_USER": postgres_user,
            "POSTGRES_IMAGE": postgres_image,
            "N8N_IMAGE": n8n_image,
            "N8N_LOG_LEVEL": n8n_log_level,
        }

        caddy_output = args.output_dir / "caddy" / f"{client_id}.caddy"
        caddy_output.parent.mkdir(parents=True, exist_ok=True)
        caddy_output.write_text(
            replace_tokens(
                caddy_template.read_text(encoding="utf-8"), tokens
            ).rstrip()
            + "\n",
            encoding="utf-8",
        )

        workflow_files = render_json_templates(
            args.template_root / "n8n" / "workflows",
            args.output_dir / "n8n" / "workflows",
            tokens,
        )
        retell_files = render_json_templates(
            args.template_root / "retell",
            args.output_dir / "retell",
            tokens,
        )

        (args.output_dir / "n8n" / "workflows").mkdir(
            parents=True, exist_ok=True
        )
        (args.output_dir / "sql").mkdir(parents=True, exist_ok=True)
        (args.output_dir / "meta").mkdir(parents=True, exist_ok=True)

        migration_files: list[str] = []
        migration_dir = args.template_root / "sql" / "migrations"
        if migration_dir.is_dir():
            for migration in sorted(migration_dir.glob("*.sql")):
                shutil.copy2(migration, args.output_dir / "sql" / migration.name)
                migration_files.append(migration.name)

        shutil.copy2(args.tenant_file, args.output_dir / "tenant.snapshot.yml")

        caddy_config = require_mapping(factory.get("caddy", {}), "factory.caddy")
        deployment = require_mapping(
            factory.get("deployment", {}), "factory.deployment"
        )

        manifest = {
            "version": 1,
            "client_id": client_id,
            "restaurant_slug": restaurant_slug,
            "tenant_path": tenant_path,
            "base_domain": base_domain,
            "public_url": f"https://{base_domain}/{tenant_path}/",
            "containers": {
                "postgres": f"{client_id}_postgres",
                "n8n": n8n_container,
            },
            "postgres": {"database": postgres_db, "user": postgres_user},
            "docker": {
                "edge_network": edge_network,
                "create_edge_network": bool(
                    factory.get("create_edge_network", False)
                ),
                "n8n_image": n8n_image,
                "postgres_image": postgres_image,
            },
            "caddy": {
                "enabled": bool(caddy_config.get("enabled", False)),
                "container_name": caddy_config.get(
                    "container_name", "edge-caddy"
                ),
                "routes_host_dir": caddy_config.get("routes_host_dir", ""),
                "container_config_path": caddy_config.get(
                    "container_config_path", "/etc/caddy/Caddyfile"
                ),
                "reload": bool(caddy_config.get("reload", True)),
            },
            "deployment": {
                "wait_timeout_seconds": int(
                    deployment.get("wait_timeout_seconds", 180)
                ),
                "import_workflows": bool(
                    deployment.get("import_workflows", True)
                ),
                "smoke_test": bool(deployment.get("smoke_test", True)),
            },
            "files": {
                "migrations": migration_files,
                "workflows": workflow_files,
                "retell": retell_files,
            },
        }

        (args.output_dir / "meta" / "manifest.json").write_text(
            json.dumps(
                manifest,
                ensure_ascii=False,
                indent=2,
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
        )

        print(f"[OK] Infrastructure générée : {args.output_dir}")
        print(f"[OK] URL : {manifest['public_url']}")
        print(f"[OK] Base : {postgres_db}")
        print(f"[OK] Réseau edge : {edge_network}")

    except ConfigError as exc:
        print(f"[ERREUR] {exc}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())

